TrajectoryPlannerROS:
  max_vel_x: 0.1
  min_vel_x: 0.04
  max_vel_theta: 0.6
  min_vel_theta: -0.6
  min_in_place_vel_theta: 0.4

  acc_lim_theta: 1.0
  acc_lim_x: 2.0
  acc_lim_y: 0.0
  
  xy_goal_tolerance: 0.1
  
  holonomic_robot: false
