DWAPlannerPOS:
  acc_lim_x: 0.01
  acc_lim_y: 0.01
  acc_lim_th: 0.01
  max_vel_x: 0.1
  min_vel_x: -0.1
  max_vel_y: 0.1
  min_vel_y: -0.1
  max_trans_vel: 0.1
  min_trans_vel: 0.04
  max_rot_vel: 0.01
  min_rot_vel: 0
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.2
